# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a22d81bf95eb61d9af556996371d0a7e618e61bcc3f1a16d94b28f382fca57dc905fa93e4257c206393aaa6089d60e54e553e78fd279fa11d98e11a99c243a

test:
  secret_key_base: f1332537e465b8c950e3ad68d7e834c4549d3d515c7fcb61f52fdfa950abce995eb55e4abe8c695687625bdcb4484c02c1faacdf03a11c37a713b6a28d15e8d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
